const hospitals = [
  {
    id: '1',
    name: 'Lagos Island General Hospital',
    specialties: ['Emergency', 'Maternity', 'Cardiology', 'Pediatrics'],
    ambulance: true,
    ambulanceContact: '+2349011111101',
    lat: 6.41,
    lng: 3.31,
  },
  {
    id: '2',
    name: 'Gbagada General Hospital',
    specialties: ['Burns', 'Orthopedics', 'Trauma', 'Cardiac Arrest'],
    ambulance: true,
    ambulanceContact: '+2349011111102',
    lat: 6.42,
    lng: 3.32,
  },
  {
    id: '3',
    name: 'Ikeja General Hospital',
    specialties: [
      'Emergency',
      'Pediatrics',
      'Gunshot Wound',
      'Pregnancy Complication',
    ],
    ambulance: true,
    ambulanceContact: '+2349011111103',
    lat: 6.43,
    lng: 3.33,
  },
  {
    id: '4',
    name: 'Ikorodu General Hospital',
    specialties: ['Emergency', 'Stroke Unit', 'Choking', 'Severe Bleeding'],
    ambulance: true,
    ambulanceContact: '+2349011111104',
    lat: 6.44,
    lng: 3.34,
  },
  {
    id: '5',
    name: 'Badagry General Hospital',
    specialties: ['Emergency', 'Trauma', 'Burns', 'Dislocation'],
    ambulance: false,
    ambulanceContact: null,
    lat: 6.45,
    lng: 3.35,
  },
  {
    id: '6',
    name: 'Amuwo-Odofin General Hospital',
    specialties: ['Maternity', 'Cardiology', 'Dislocation', 'Choking'],
    ambulance: false,
    ambulanceContact: null,
    lat: 6.46,
    lng: 3.36,
  },
  {
    id: '7',
    name: 'Eti-Osa Maternal and Child Care Centre',
    specialties: [
      'Emergency',
      'Pregnancy Complication',
      'Pediatrics',
      'Maternity',
    ],
    ambulance: true,
    ambulanceContact: '+2349011111107',
    lat: 6.47,
    lng: 3.37,
  },
  {
    id: '8',
    name: 'Alimosho General Hospital',
    specialties: ['Emergency', 'Burns', 'Gunshot Wound', 'Cardiac Arrest'],
    ambulance: false,
    ambulanceContact: null,
    lat: 6.48,
    lng: 3.38,
  },
  {
    id: '9',
    name: 'Epe General Hospital',
    specialties: ['Emergency', 'Orthopedics', 'Dislocation', 'Gunshot Wound'],
    ambulance: true,
    ambulanceContact: '+2349011111109',
    lat: 6.49,
    lng: 3.39,
  },
  {
    id: '10',
    name: 'Ifako-Ijaiye General Hospital',
    specialties: ['Pediatrics', 'Maternity', 'Severe Bleeding', 'Cardiology'],
    ambulance: true,
    ambulanceContact: '+2349011111110',
    lat: 6.5,
    lng: 3.4,
  },
  {
    id: '11',
    name: 'Mushin General Hospital',
    specialties: ['Emergency', 'Dislocation', 'Burns', 'Choking'],
    ambulance: false,
    ambulanceContact: null,
    lat: 6.51,
    lng: 3.41,
  },
  {
    id: '12',
    name: 'Ojo General Hospital',
    specialties: [
      'Pregnancy Complication',
      'Gunshot Wound',
      'Cardiac Arrest',
      'Burns',
    ],
    ambulance: true,
    ambulanceContact: '+2349011111112',
    lat: 6.52,
    lng: 3.42,
  },
  {
    id: '13',
    name: 'Isolo General Hospital',
    specialties: ['Stroke Unit', 'Trauma', 'Pediatrics', 'Emergency'],
    ambulance: false,
    ambulanceContact: null,
    lat: 6.53,
    lng: 3.43,
  },
  {
    id: '14',
    name: 'Ajeromi General Hospital',
    specialties: ['Dislocation', 'Maternity', 'Cardiology', 'Burn Unit'],
    ambulance: false,
    ambulanceContact: null,
    lat: 6.54,
    lng: 3.44,
  },
  {
    id: '15',
    name: 'Agege General Hospital',
    specialties: ['Gunshot Wound', 'Emergency', 'Trauma', 'Burns'],
    ambulance: true,
    ambulanceContact: '+2349011111115',
    lat: 6.55,
    lng: 3.45,
  },
  {
    id: '16',
    name: 'Surulere General Hospital',
    specialties: ['Maternity', 'Pediatrics', 'Cardiology', 'Stroke Unit'],
    ambulance: true,
    ambulanceContact: '+2349011111116',
    lat: 6.56,
    lng: 3.46,
  },
  {
    id: '17',
    name: 'Shomolu Health Centre',
    specialties: ['Emergency', 'Dislocation', 'Severe Bleeding', 'Choking'],
    ambulance: false,
    ambulanceContact: null,
    lat: 6.57,
    lng: 3.47,
  },
  {
    id: '18',
    name: 'Yaba Psychiatric Hospital',
    specialties: ['Emergency', 'Trauma', 'Cardiology', 'Burns'],
    ambulance: true,
    ambulanceContact: '+2349011111118',
    lat: 6.58,
    lng: 3.48,
  },
  {
    id: '19',
    name: 'Bariga Health Centre',
    specialties: ['Gunshot Wound', 'Burns', 'Cardiology', 'Pediatrics'],
    ambulance: false,
    ambulanceContact: null,
    lat: 6.59,
    lng: 3.49,
  },
  {
    id: '20',
    name: 'Ajah General Hospital',
    specialties: [
      'Dislocation',
      'Pregnancy Complication',
      'Stroke Unit',
      'Cardiology',
    ],
    ambulance: true,
    ambulanceContact: '+2349011111120',
    lat: 6.6,
    lng: 3.5,
  },
  {
    id: '21',
    name: 'Festac Town Health Centre',
    specialties: ['Maternity', 'Gunshot Wound', 'Choking', 'Pediatrics'],
    ambulance: false,
    ambulanceContact: null,
    lat: 6.61,
    lng: 3.51,
  },
  {
    id: '22',
    name: 'Iyana Ipaja General Hospital',
    specialties: ['Emergency', 'Cardiology', 'Orthopedics', 'Stroke Unit'],
    ambulance: true,
    ambulanceContact: '+2349011111122',
    lat: 6.62,
    lng: 3.52,
  },
  {
    id: '23',
    name: 'Ketu General Hospital',
    specialties: ['Gunshot Wound', 'Burn Unit', 'Dislocation', 'Trauma'],
    ambulance: false,
    ambulanceContact: null,
    lat: 6.63,
    lng: 3.53,
  },
  {
    id: '24',
    name: 'Ojodu General Hospital',
    specialties: [
      'Emergency',
      'Cardiac Arrest',
      'Pregnancy Complication',
      'Pediatrics',
    ],
    ambulance: true,
    ambulanceContact: '+2349011111124',
    lat: 6.64,
    lng: 3.54,
  },
  {
    id: '25',
    name: 'Abule Egba Health Centre',
    specialties: ['Stroke Unit', 'Burns', 'Orthopedics', 'Maternity'],
    ambulance: false,
    ambulanceContact: null,
    lat: 6.65,
    lng: 3.55,
  },
  {
    id: '26',
    name: 'Wuse District Hospital',
    specialties: ['Emergency', 'Gunshot Wound', 'Trauma', 'Cardiology'],
    ambulance: true,
    ambulanceContact: '+2349022222201',
    lat: 9.26,
    lng: 7.66,
  },
  {
    id: '27',
    name: 'Asokoro District Hospital',
    specialties: [
      'Burn Unit',
      'Cardiac Arrest',
      'Choking',
      'Pregnancy Complication',
    ],
    ambulance: true,
    ambulanceContact: '+2349022222202',
    lat: 9.27,
    lng: 7.67,
  },
  {
    id: '28',
    name: 'Garki Hospital',
    specialties: ['Neurosurgery', 'Emergency', 'Pediatrics', 'Stroke Unit'],
    ambulance: true,
    ambulanceContact: '+2349022222203',
    lat: 9.28,
    lng: 7.68,
  },
  {
    id: '29',
    name: 'Maitama District Hospital',
    specialties: ['Emergency', 'Burns', 'Cardiology', 'Trauma'],
    ambulance: false,
    ambulanceContact: null,
    lat: 9.29,
    lng: 7.69,
  },
  {
    id: '30',
    name: 'Kubwa General Hospital',
    specialties: [
      'Emergency',
      'Orthopedics',
      'Gunshot Wound',
      'Cardiac Arrest',
    ],
    ambulance: true,
    ambulanceContact: '+2349022222205',
    lat: 9.3,
    lng: 7.7,
  },
  {
    id: '31',
    name: 'Abuja National Hospital',
    specialties: ['Trauma', 'Pediatrics', 'Burns', 'Emergency'],
    ambulance: true,
    ambulanceContact: '+2349022222206',
    lat: 9.31,
    lng: 7.71,
  },
  {
    id: '32',
    name: 'Zuba General Hospital',
    specialties: ['Dislocation', 'Severe Bleeding', 'Gunshot Wound', 'Burns'],
    ambulance: false,
    ambulanceContact: null,
    lat: 9.32,
    lng: 7.72,
  },
  {
    id: '33',
    name: 'Nyanya General Hospital',
    specialties: [
      'Emergency',
      'Cardiology',
      'Pregnancy Complication',
      'Pediatrics',
    ],
    ambulance: true,
    ambulanceContact: '+2349022222208',
    lat: 9.33,
    lng: 7.73,
  },
  {
    id: '34',
    name: 'Bwari General Hospital',
    specialties: [
      'Emergency',
      'Orthopedics',
      'Gunshot Wound',
      'Cardiac Arrest',
    ],
    ambulance: true,
    ambulanceContact: '+2349022222209',
    lat: 9.34,
    lng: 7.74,
  },
  {
    id: '35',
    name: 'Lugbe General Hospital',
    specialties: ['Emergency', 'Choking', 'Burn Unit', 'Maternity'],
    ambulance: false,
    ambulanceContact: null,
    lat: 9.35,
    lng: 7.75,
  },
  {
    id: '36',
    name: 'Karu General Hospital',
    specialties: [
      'Pregnancy Complication',
      'Stroke Unit',
      'Gunshot Wound',
      'Burns',
    ],
    ambulance: true,
    ambulanceContact: '+2349022222211',
    lat: 9.36,
    lng: 7.76,
  },
  {
    id: '37',
    name: 'Gwagwalada Teaching Hospital',
    specialties: ['Emergency', 'Orthopedics', 'Cardiology', 'Burns'],
    ambulance: true,
    ambulanceContact: '+2349022222212',
    lat: 9.37,
    lng: 7.77,
  },
  {
    id: '38',
    name: 'Jabi Clinic',
    specialties: ['Maternity', 'Pediatrics', 'Severe Bleeding', 'Burns'],
    ambulance: false,
    ambulanceContact: null,
    lat: 9.38,
    lng: 7.78,
  },
  {
    id: '39',
    name: 'Life Camp General Hospital',
    specialties: ['Cardiology', 'Choking', 'Burn Unit', 'Emergency'],
    ambulance: true,
    ambulanceContact: '+2349022222214',
    lat: 9.39,
    lng: 7.79,
  },
  {
    id: '40',
    name: 'Durumi Health Centre',
    specialties: ['Orthopedics', 'Gunshot Wound', 'Burns', 'Stroke Unit'],
    ambulance: false,
    ambulanceContact: null,
    lat: 9.4,
    lng: 7.8,
  },
  {
    id: '41',
    name: 'Utako District Hospital',
    specialties: ['Emergency', 'Pediatrics', 'Burn Unit', 'Cardiology'],
    ambulance: true,
    ambulanceContact: '+2349022222216',
    lat: 9.41,
    lng: 7.81,
  },
  {
    id: '42',
    name: 'Mpape Health Centre',
    specialties: [
      'Cardiology',
      'Pregnancy Complication',
      'Burns',
      'Stroke Unit',
    ],
    ambulance: false,
    ambulanceContact: null,
    lat: 9.42,
    lng: 7.82,
  },
  {
    id: '43',
    name: 'Gwarinpa General Hospital',
    specialties: ['Dislocation', 'Gunshot Wound', 'Trauma', 'Emergency'],
    ambulance: true,
    ambulanceContact: '+2349022222218',
    lat: 9.43,
    lng: 7.83,
  },
  {
    id: '44',
    name: 'Apo General Hospital',
    specialties: ['Emergency', 'Choking', 'Burns', 'Pediatrics'],
    ambulance: true,
    ambulanceContact: '+2349022222219',
    lat: 9.44,
    lng: 7.84,
  },
  {
    id: '45',
    name: 'Kuje General Hospital',
    specialties: [
      'Cardiology',
      'Pregnancy Complication',
      'Maternity',
      'Emergency',
    ],
    ambulance: false,
    ambulanceContact: null,
    lat: 9.45,
    lng: 7.85,
  },
  {
    id: '46',
    name: 'Dutse Alhaji Health Centre',
    specialties: [
      'Burn Unit',
      'Gunshot Wound',
      'Cardiology',
      'Severe Bleeding',
    ],
    ambulance: true,
    ambulanceContact: '+2349022222221',
    lat: 9.46,
    lng: 7.86,
  },
  {
    id: '47',
    name: 'Dei-Dei Health Centre',
    specialties: ['Trauma', 'Orthopedics', 'Stroke Unit', 'Gunshot Wound'],
    ambulance: false,
    ambulanceContact: null,
    lat: 9.47,
    lng: 7.87,
  },
  {
    id: '48',
    name: 'Orozo Clinic',
    specialties: ['Emergency', 'Burns', 'Dislocation', 'Choking'],
    ambulance: true,
    ambulanceContact: '+2349022222223',
    lat: 9.48,
    lng: 7.88,
  },
  {
    id: '49',
    name: 'Galadimawa Health Centre',
    specialties: [
      'Pregnancy Complication',
      'Burn Unit',
      'Emergency',
      'Cardiac Arrest',
    ],
    ambulance: false,
    ambulanceContact: null,
    lat: 9.49,
    lng: 7.89,
  },
  {
    id: '50',
    name: 'Jahi Health Center',
    specialties: [
      'Emergency',
      'Burn Unit',
      'Cardiac Arrest',
      'Severe Bleeding',
    ],
    ambulance: false,
    ambulanceContact: null,
    lat: 9.5,
    lng: 7.9,
  },
]

export default hospitals
